//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QSC_Test_Automation.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Aaa111*")]
        public string DevicePassword {
            get {
                return ((string)(this["DevicePassword"]));
            }
            set {
                this["DevicePassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("QATadmin")]
        public string DeviceUsername {
            get {
                return ((string)(this["DeviceUsername"]));
            }
            set {
                this["DeviceUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8.0")]
        public string CompareFirmwareVersion {
            get {
                return ((string)(this["CompareFirmwareVersion"]));
            }
            set {
                this["CompareFirmwareVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("root")]
        public string TelnetUserName {
            get {
                return ((string)(this["TelnetUserName"]));
            }
            set {
                this["TelnetUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("decline")]
        public string TelnetPassword {
            get {
                return ((string)(this["TelnetPassword"]));
            }
            set {
                this["TelnetPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Designversion {
            get {
                return ((string)(this["Designversion"]));
            }
            set {
                this["Designversion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Qsyscheckbox {
            get {
                return ((string)(this["Qsyscheckbox"]));
            }
            set {
                this["Qsyscheckbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Qsystemppath {
            get {
                return ((string)(this["Qsystemppath"]));
            }
            set {
                this["Qsystemppath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TesterName {
            get {
                return ((string)(this["TesterName"]));
            }
            set {
                this["TesterName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Category {
            get {
                return ((string)(this["Category"]));
            }
            set {
                this["Category"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Restorecheckbox {
            get {
                return ((string)(this["Restorecheckbox"]));
            }
            set {
                this["Restorecheckbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AfterTestCaseFails {
            get {
                return ((bool)(this["AfterTestCaseFails"]));
            }
            set {
                this["AfterTestCaseFails"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutomationPauses {
            get {
                return ((bool)(this["AutomationPauses"]));
            }
            set {
                this["AutomationPauses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AfterExecutionCompletion {
            get {
                return ((bool)(this["AfterExecutionCompletion"]));
            }
            set {
                this["AfterExecutionCompletion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ApplicationCrashes {
            get {
                return ((bool)(this["ApplicationCrashes"]));
            }
            set {
                this["ApplicationCrashes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ReportEmailID {
            get {
                return ((string)(this["ReportEmailID"]));
            }
            set {
                this["ReportEmailID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TestCaseFailsCount {
            get {
                return ((int)(this["TestCaseFailsCount"]));
            }
            set {
                this["TestCaseFailsCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool upgradeedr {
            get {
                return ((bool)(this["upgradeedr"]));
            }
            set {
                this["upgradeedr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" E:\\test")]
        public string Path {
            get {
                return ((string)(this["Path"]));
            }
            set {
                this["Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Bank Control,Input,-Output,*Bank Control,=BANK_CONTROL_INPUT ;Bank Control,Output,Input,*Bank Control,=BANK_CONTROL_INPUT_OUTPUT ;Bank Control,Output,-Input,*Bank Control,=BANK_CONTROL_OUTPUT ;Bank Select,Input,*Bank Select,=BANK_SELECT_INPUT ;Bank Select,Output,*Bank Select,=BANK_SELECT_OUTPUT ;Channel,*Channel,=CHANNEL ; GPIO,Input,-Out,*GPIO,=GPIO_INPUT ;GPIO,Out,-Input,*GPIO,=GPIO_OUTPUT ;Input,-Output,*Input,-Bank Control,-Bank Select,-GPIO,=INPUT ;Input,Output,*Input,-Bank Control,-Bank Select,-GPIO,=INPUT_OUTPUT ;Output,-Input,*Output,-Bank Control,-Bank Select,-GPIO,=OUTPUT ;Output,Input,*Output,-Bank Control,-Bank Select,-GPIO,=OUTPUT_INPUT ;Tap,*Tap,=TAP ;")]
        public string QATPrefix {
            get {
                return ((string)(this["QATPrefix"]));
            }
            set {
                this["QATPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.youtube.com/channel/UC-R9BKbnhoDAK2KHG9Jy5sg")]
        public string YouTubeLink {
            get {
                return ((string)(this["YouTubeLink"]));
            }
            set {
                this["YouTubeLink"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\1usbrsqadbd01\\\\SQA_QAT_Server")]
        public string ServerPathBDR {
            get {
                return ((string)(this["ServerPathBDR"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://1usbrsqadbd01/SQA_QAT_Server/")]
        public string ReportlinkBDR {
            get {
                return ((string)(this["ReportlinkBDR"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\1usbrsqadbd01\\SQA_QAT_Server\\QATsetup")]
        public string ReleaseFolderBDR {
            get {
                return ((string)(this["ReleaseFolderBDR"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string currentserver {
            get {
                return ((string)(this["currentserver"]));
            }
            set {
                this["currentserver"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\1uscmsqadbd01\\\\SQA_QAT_Server")]
        public string ServerPathCM {
            get {
                return ((string)(this["ServerPathCM"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://1uscmsqadbd01/SQA_QAT_Server/")]
        public string ReportlinkCM {
            get {
                return ((string)(this["ReportlinkCM"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\1uscmsqadbd01\\SQA_QAT_Server\\QATsetup")]
        public string ReleaseFolderCM {
            get {
                return ((string)(this["ReleaseFolderCM"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ServerSwitch {
            get {
                return ((bool)(this["ServerSwitch"]));
            }
            set {
                this["ServerSwitch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\1uscmsqadbd01\\\\SQA_QAT_Server")]
        public string ServerPath {
            get {
                return ((string)(this["ServerPath"]));
            }
            set {
                this["ServerPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://1uscmsqadbd01/SQA_QAT_Server/")]
        public string Reportlink {
            get {
                return ((string)(this["Reportlink"]));
            }
            set {
                this["Reportlink"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\1uscmsqadbd01\\SQA_QAT_Server\\QATsetup")]
        public string ReleaseFolder {
            get {
                return ((string)(this["ReleaseFolder"]));
            }
            set {
                this["ReleaseFolder"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://1uscmsqadbd01/SQA_QAT_Server/")]
        public string ReportlinkOthers {
            get {
                return ((string)(this["ReportlinkOthers"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\1uscmsqadbd01\\SQA_QAT_Server\\QATsetup")]
        public string ReleaseFolderOthers {
            get {
                return ((string)(this["ReleaseFolderOthers"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ReportEmailSubject {
            get {
                return ((string)(this["ReportEmailSubject"]));
            }
            set {
                this["ReportEmailSubject"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\1usbrsqadbd01\\\\SQA_QAT_Sandbox")]
        public string SandboxPathBDR {
            get {
                return ((string)(this["SandboxPathBDR"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Bypass_time {
            get {
                return ((int)(this["Bypass_time"]));
            }
            set {
                this["Bypass_time"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Bypass_checkvalue {
            get {
                return ((bool)(this["Bypass_checkvalue"]));
            }
            set {
                this["Bypass_checkvalue"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\qscserver\\QSC_Manual\\TestDesigns")]
        public string ServerPathJAS {
            get {
                return ((string)(this["ServerPathJAS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://qscserver/reports/")]
        public string ReportlinkJAS {
            get {
                return ((string)(this["ReportlinkJAS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\qscserver\\QSC_Manual\\QATsetup")]
        public string ReleaseFolderJAS {
            get {
                return ((string)(this["ReleaseFolderJAS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\qscserver\\Sandbox")]
        public string SandboxPathJAS {
            get {
                return ((string)(this["SandboxPathJAS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://1usbrsqadbd01/SQA_QAT_Server/?DB=Sandbox")]
        public string ReportlinkBDR_sandbox {
            get {
                return ((string)(this["ReportlinkBDR_sandbox"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://qscserver/reports/?DB=Sandbox")]
        public string ReportlinkJAS_sandbox {
            get {
                return ((string)(this["ReportlinkJAS_sandbox"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://1uscmsqadbd01/SQA_QAT_Server/?DB=Sandbox")]
        public string ReportlinkCM_sandbox {
            get {
                return ((string)(this["ReportlinkCM_sandbox"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\1uscmsqadbd01\\\\SQA_QAT_Sandbox")]
        public string SandboxPathCM {
            get {
                return ((string)(this["SandboxPathCM"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TelnetPreference {
            get {
                return ((bool)(this["TelnetPreference"]));
            }
            set {
                this["TelnetPreference"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"I/O-22,DPA4.2Q,DPA4.3Q,DPA4.5Q,I/O-Frame,I/O-Frame8S,PS-400H,PS-800H,PS-1600H,PS-1650H,TSC-8,TSC-7,CXD4.3Q,PTZ-12x72,PTZ-20x60,CXD4.2Q,I/O-USB-Bridge,TSC-47-G2,TSC-3,PS-400G,I/O-510i,CXD4.5Q,VS3x2MD,CXD8.8Q,DCIO,DCIO-H,TSC-7t,TSC-7w, I/O-8 Flex,CXD8.4Q,TSC-116-G2")]
        public string Netpairlist {
            get {
                return ((string)(this["Netpairlist"]));
            }
            set {
                this["Netpairlist"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool email_link {
            get {
                return ((bool)(this["email_link"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MailIdSwitch {
            get {
                return ((bool)(this["MailIdSwitch"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Execution_dev_mode {
            get {
                return ((bool)(this["Execution_dev_mode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Core_Password_Skip {
            get {
                return ((bool)(this["Core_Password_Skip"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int Autoevent_wait_time {
            get {
                return ((int)(this["Autoevent_wait_time"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int Ssh_Command_Execution_timeout {
            get {
                return ((int)(this["Ssh_Command_Execution_timeout"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("portrange=&notport=false&disablemcast=false&pktlen=&capsize=100")]
        public string PcapFilter {
            get {
                return ((string)(this["PcapFilter"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int Dev_mode_ssh_delay {
            get {
                return ((int)(this["Dev_mode_ssh_delay"]));
            }
            set {
                this["Dev_mode_ssh_delay"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int Deploy_time_upperlimit {
            get {
                return ((int)(this["Deploy_time_upperlimit"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public int FirmwareTime_upperlimit {
            get {
                return ((int)(this["FirmwareTime_upperlimit"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("eyJrIjoiV1JzN1pjNloxeG5PenlRbjVBUlNiSXdraEZ2bjk1blkiLCJuIjoiUUFUX0tleSIsImlkIjoxf" +
            "Q==")]
        public string API_key_JAS {
            get {
                return ((string)(this["API_key_JAS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("eyJrIjoieUR1Y2ZzMDJWNEVSdlV0NXhZeVN5YklTYmQ5UUhpdE8iLCJuIjoiYWRtaW4iLCJpZCI6MX0=")]
        public string API_key_CM {
            get {
                return ((string)(this["API_key_CM"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("eyJrIjoiUGFrS1htRFVrVWduMUVWN3JjUnptV1g2UE9ja2JMWm8iLCJuIjoiYWRtaW4iLCJpZCI6MX0=")]
        public string API_key_BDR {
            get {
                return ((string)(this["API_key_BDR"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BrowserPath {
            get {
                return ((string)(this["BrowserPath"]));
            }
            set {
                this["BrowserPath"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8.3")]
        public string DigestFirmwareVersion {
            get {
                return ((string)(this["DigestFirmwareVersion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8.4")]
        public string NewDepolySchemeFirmwareVersion {
            get {
                return ((string)(this["NewDepolySchemeFirmwareVersion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GrafanaPlotly {
            get {
                return ((bool)(this["GrafanaPlotly"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public int Delay_after_connect {
            get {
                return ((int)(this["Delay_after_connect"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AddreportLink {
            get {
                return ((bool)(this["AddreportLink"]));
            }
            set {
                this["AddreportLink"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gurutn")]
        public string OthersHostMachineName {
            get {
                return ((string)(this["OthersHostMachineName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\inbgdsqrem1-w10\\SQA_QAT_Server\\QATsetup")]
        public string ReleaseFolderBLR {
            get {
                return ((string)(this["ReleaseFolderBLR"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\inbgdsqrem1-w10\\SQA_QAT_Sandbox")]
        public string SandboxPathBLR {
            get {
                return ((string)(this["SandboxPathBLR"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://inbgdsqrem1-w10/SQA_QAT_Server/?DB=Sandbox")]
        public string ReportlinkBLR_sandbox {
            get {
                return ((string)(this["ReportlinkBLR_sandbox"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ServerPathBLR {
            get {
                return ((string)(this["ServerPathBLR"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://inbgdsqrem1-w10/SQA_QAT_Server/")]
        public string ReportlinkBLR {
            get {
                return ((string)(this["ReportlinkBLR"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("eyJrIjoiMXBqV3pKTmZ3VVlTeGRUaVgyVm1CZ1plamJLTmd2RDciLCJuIjoiUUFUX0JhbmdhbG9yZSIsI" +
            "mlkIjoxfQ==")]
        public string API_key_BLR {
            get {
                return ((string)(this["API_key_BLR"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("eyJrIjoiNlVaOUlNOUhJWm5pTGhuVDZjVHdmTVlXUkRMTEVzZ3IiLCJuIjoiVGVzdCIsImlkIjoxfQ==")]
        public string API_key_Others {
            get {
                return ((string)(this["API_key_Others"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DeployMonitor_TotaltimeOnly {
            get {
                return ((bool)(this["DeployMonitor_TotaltimeOnly"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9.2")]
        public string NewPeripheralFirmwareVersion {
            get {
                return ((string)(this["NewPeripheralFirmwareVersion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=nodata;user=sa;password=nodata")]
        public string ConstringJAS {
            get {
                return ((string)(this["ConstringJAS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=nodata;user=sa;password=nodata")]
        public string ConstringCM {
            get {
                return ((string)(this["ConstringCM"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=nodata;user=sa;password=nodata")]
        public string ConstringBDR {
            get {
                return ((string)(this["ConstringBDR"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RunnerSandboxTestDB")]
        public string RunnerDB_SANDBOX {
            get {
                return ((string)(this["RunnerDB_SANDBOX"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DesignerSandboxTestDB")]
        public string DesignerDB_SANDBOX {
            get {
                return ((string)(this["DesignerDB_SANDBOX"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OTHERS")]
        public string availableservers {
            get {
                return ((string)(this["availableservers"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GrafanaSandboxTestDB")]
        public string GrafanaDB_SANDBOX {
            get {
                return ((string)(this["GrafanaDB_SANDBOX"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DebugMode {
            get {
                return ((bool)(this["DebugMode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\joyce\\QATserver")]
        public string ServerPathOthers {
            get {
                return ((string)(this["ServerPathOthers"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GrafanaTestDB")]
        public string GrafanaDB {
            get {
                return ((string)(this["GrafanaDB"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RunnerTestDB")]
        public string RunnerDB {
            get {
                return ((string)(this["RunnerDB"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DesignerTestDB")]
        public string DesignerDB {
            get {
                return ((string)(this["DesignerDB"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=nodata;user=sa;password=nodata")]
        public string ConstringBLR {
            get {
                return ((string)(this["ConstringBLR"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("qa.reflect.qsc.com")]
        public string QREMreflectLink {
            get {
                return ((string)(this["QREMreflectLink"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("guru.tn@qsc.com")]
        public string QREMUserName {
            get {
                return ((string)(this["QREMUserName"]));
            }
            set {
                this["QREMUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Jasmin@123")]
        public string QREMPassword {
            get {
                return ((string)(this["QREMPassword"]));
            }
            set {
                this["QREMPassword"] = value;
            }
        }
    }
}
